### ISSUE TITLE
How to use it with python ?

### ISSUE THREAD

**Issue by JeanMenage** [pnxenopoulos/csgonavparse#1]
Hi, i was wondering, how to use it with python ? Thank you !

**Comment by pnxenopoulos** [comment]
Hi @JeanMenage, please check out the [csgo](https://github.com/pnxenopoulos/csgo) package. You can access a dictionary of distances for a given map using `from csgo import DIST_DICT`.

**Comment by JeanMenage** [comment]
> Hi @JeanMenage, please check out the [csgo](https://github.com/pnxenopoulos/csgo) package. You can access a dictionary of distances for a given map using `from csgo import DIST_DICT`.

Aight, thanks ! Do you have any documentation or something about this function ? I searched about it on the csgo package page but i couldn't find it. Thanks

Edit: I found what i wanted here: https://github.com/pnxenopoulos/csgo/tree/master/csgo/analytics
Thanks for all your work and have a nice day !
